name: u-root-buildcheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Cancel running workflows on new push to a PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        template: ["core", "boot core", "world", "cpu"]
        arch: [amd64, arm, arm64, riscv64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: |
          go install github.com/u-root/mkuimage/cmd/mkuimage@latest
          go install github.com/hugelgupf/vmtest/tools/runvmtest@latest
          GOARCH=${{ matrix.arch }} mkuimage -config=default \
            ${{ matrix.template }}
          runvmtest -- bash -c "cp \$VMTEST_KERNEL ./kernel-x86_64"
